### ISSUE TITLE
Game states that my mods are not up to date/failed to load

### ISSUE THREAD

**Issue by etcwebdesigns** [Ellpeck/TinyLifeExampleMod#3]
Problem is I have mods allowed but none installed, the 3 it says that failed to load are InterestMod, NebAdditionalFurniture and Tiny Scene. I did just add 2 mods and they apparently are not up to date with the game.

**Comment by Ellpeck** [comment]
Hi! None of these things appear to be issues with the example mod, so I'm not sure why you're reporting this here.

It sounds like your first issue is that the game is claiming there are mods installed when there really aren't - this is likely due to the fact that you downloaded the mods through Steam Workshop, and they have not been removed from your game yet. To remove items that you downloaded from the workshop, make sure to start the game while Steam is running and give it some time after startup to remove the items you unsubscribed from. If that doesn't fix it, please report the issue through the [feedback form](https://tinylifegame.com/bugreport).

For any mods that aren't up to date, please report that to the mods' individual issue trackers (or, if they don't have any, their download sites like the Steam workshop).

Thanks so much!! :)
